site_name: topoGenesis
theme:
  name: "material"
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
plugins:
  - search
  - mkdocstrings:
      watch:
        - topogenesis
      handlers:
        python:
          selection:
            filters:
              - "!^_" # exlude all members starting with _
nav:
  - Home: "index.md"
  - Installation: "installation.md"
  - Tutorials: "tutorials.md"
  - API:
      - Data Structures:
          - Lattice: api/datastructures/lattice.md
          - Stencil: api/datastructures/stencil.md
          - Cloud: api/datastructures/cloud.md
      - "Geometry": "api/geometry.md"
  - About:
      - "License": "license.md"
      - "Citing": "citing.md"
